### ISSUE TITLE
why

### ISSUE THREAD

**Issue by GoldenCorgi** [callistachang/callistachang#1]
this repo entirely disasterous and risky for my employment opportunity

this is an emergency

**Comment by GoldenCorgi** [comment]
oops i accidentally closed the issue

for just one night, can u help me [open mine](https://www.youtube.com/watch?v=3zFS-V_iCiM)?

**Comment by callistachang** [comment]
@GoldenCorgi no worries, i will reopen it, feel free to work on it! 😃 

a/n: oh so that's what you meant by the [open mind](https://youtu.be/dQw4w9WgXcQ) jokes

**Comment by GoldenCorgi** [comment]
u can close other issues

but u should open mine curl
